name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:   "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release: "jammy"                        # Userspace
          armbian_target:  "build"                        # Options: build=image, kernel=kernel
          armbian_board:   "orangepizero3"                # Build target
        env:
          BUILD_DESKTOP: "no"
